parser: "@typescript-eslint/parser"
extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended

plugins:
  - simple-import-sort

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/no-explicit-any': off
